language: node_js
cache:
   directories:
   - node_modules

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libffi-dev libssl-dev

install:
  - nvm install 8.4.0
  - nvm use 8.4.0
  - node --version
  - npm install -g npm@5.3.0
  - npm install -g hexo-cli
  - npm install
  - pip install pyopenssl yaml requests

before_script:
  - git submodule update --init --recursive
  - git config user.name "tenfyzhong"
  - git config user.email "tenfyzhong@qq.com"
  - sed -i "s/https:\/\/\(github\.com\/tenfyzhong\/tenfyzhong\.github\.io\.git\)/https:\/\/$ACCESS_TOKEN@\1/" _config.yml

script:
  - hexo clean
  - hexo g
  - hexo d
  - python init_comment.py
